Login
wolox-training/jm-angularjs pull request #12
Opened 2021-05-13 20:43 UTC by Julianhm9612

## Summary
- Added new login view
- Added some styles to login
- Added new styles for inputs and buttons
- Added new color variable

## Screenshot
<img width="872" alt="Captura de Pantalla 2021-05-13 a la(s) 3 41 35 p  m" src="https://user-images.githubusercontent.com/24255842/118185059-b6d03f00-b401-11eb-8d27-f4496259300a.png">

## Trello Card
https://trello.com/c/R2GuW3V9/32-login

2021-05-14 19:55 UTC, mcallegari10 requested changes

2021-05-14 19:55 UTC, mcallegari10 commented on books/login.html
> +                    <button class="button primary" type="button">Login</button>
type submit

2021-05-14 19:55 UTC, mcallegari10 commented on books/login.html
> +                    <button class="button secondary" type="button">Sign Up</button>
Maybe this should be a link tag 🤔

2021-05-14 19:55 UTC, mcallegari10 commented on books/scss/styles.scss
> +  display: block;
Is this needed? 🤔

2021-05-14 19:55 UTC, mcallegari10 commented on books/scss/login.scss
> +      border-bottom: 2px solid #A8A8A8;
Remember to use variables for colors

2021-05-15 00:50 UTC, Julianhm9612 commented on books/login.html
> +                    <button class="button primary" type="button">Login</button>
Have been added

2021-05-15 00:52 UTC, Julianhm9612 commented on books/login.html
> +                    <button class="button secondary" type="button">Sign Up</button>
Has been changed :relaxed:

2021-05-15 01:05 UTC, Julianhm9612 commented on books/scss/styles.scss
> +  display: block;
It has been removed

2021-05-15 01:06 UTC, Julianhm9612 commented on books/scss/login.scss
> +      border-bottom: 2px solid #A8A8A8;
Has been changed

2021-05-26 12:52 UTC, mcallegari10 approved these changes

2021-05-26 13:44 UTC, merged