Book list
wolox-training/jm-angularjs pull request #9
Opened 2021-05-12 00:09 UTC by Julianhm9612

## Summary
- Added a new view in HTML to the book list
- Added some styles to format the grid of books
- Added new styles for titles and subheads

## Screenshot
<img width="1149" alt="Captura de Pantalla 2021-05-11 a la(s) 7 01 10 p  m" src="https://user-images.githubusercontent.com/24255842/117899066-fb39ce80-b28b-11eb-996e-c679d93d4ccc.png">

## Trello Card
https://trello.com/c/5JrafDPh/30-listado-de-libros

2021-05-14 19:38 UTC, mcallegari10 requested changes

2021-05-14 19:38 UTC, mcallegari10 commented on books/scss/list.scss
> +}
Remember to add the EOF line

2021-05-14 19:38 UTC, mcallegari10 commented on books/scss/list.scss
> +  max-width: 888px;
Are Yyu sure about that size?

2021-05-14 19:38 UTC, mcallegari10 commented on books/scss/list.scss
> +    flex: 0 1 20%;
Why this flex?

2021-05-14 21:39 UTC, Julianhm9612 commented on books/scss/list.scss
> +  max-width: 888px;
Have been improved

2021-05-14 21:40 UTC, Julianhm9612 commented on books/scss/list.scss
> +}
Have been improved

2021-05-14 21:41 UTC, Julianhm9612 commented on books/scss/list.scss
> +    flex: 0 1 20%;
Was changed to a max-width :D

2021-05-17 19:11 UTC, mcallegari10 approved these changes

2021-05-17 19:51 UTC, merged